### PR TITLE
AvroEx.Schema.Parser - Hand-rolled schema parser

### LINKED ISSUE #40: Remove Ecto as a dependency
Ecto is a big library and makes `avro_ex` heavy-weight for what it is. I wanted to rewrite the schema validation portion to not use ecto, which I believe would be a breaking change and possibly controversial. I wanted to get some opinions before I took a crack at it

### LINKED ISSUE #55: Better error for named top-level union
Top-level unions cannot be named (I think?). The current behavior needs to be adjusted accordingly to what the spec says.

Possibly helpful https://github.com/fastavro/fastavro/issues/388

```elixir
     test/encode_test.exs:393
     ** (FunctionClauseError) no function clause matching in AvroEx.Schema.cast/1

     The following arguments were given to AvroEx.Schema.cast/1:
     
         # 1
         %{"name" => "maybe_null", "type" => ["null", "string"]}
     
     Attempted function clauses (showing 10 out of 25):
     
         def cast(nil)
         def cast("null")
         def cast("boolean")
         def cast("int")
         def cast("long")
         def cast("float")
         def cast("double")
         def cast("bytes")
         def cast("string")
         def cast(%{"type" => nil} = data)
         ...
         (15 clauses not shown)
     
     code: schema = AvroEx.parse_schema!(~S({"type": ["null", "string"], "name": "maybe_null"}))
     stacktrace:
```

### LINKED ISSUE #60: Records without a name fail poorly
If you have a record without a `name` field, you'll get an error like

```elixir
** (FunctionClauseError) no function clause matching in Ecto.Changeset.add_error/4

    The following arguments were given to Ecto.Changeset.add_error/4:

        # 1
        #Ecto.Changeset<action: nil, changes: %{name: "match", type: %{"fields" => [%{"name" => "uuid", "type" => "string"}, %{"name" => "type", "type" => "string"}, %{"name" => "league", "type" => "string"}], "type" => "record"}}, errors: [], data: #AvroEx.Schema.Record.Field<>, valid?: true>

        # 2
        :type

        # 3
        %{name: ["can't be blank"]}

        # 4
        []

    Attempted function clauses (showing 1 out of 1):

        def add_error(%Ecto.Changeset{errors: errors} = changeset, key, message, keys) when is_binary(message)

    (ecto 3.7.1) lib/ecto/changeset.ex:1665: Ecto.Changeset.add_error/4
    (ecto 3.7.1) lib/ecto/changeset.ex:851: anonymous fn/4 in Ecto.Changeset.on_cast_default/2
    (ecto 3.7.1) lib/ecto/changeset/relation.ex:137: Ecto.Changeset.Relation.do_cast/6
    (ecto 3.7.1) lib/ecto/changeset/relation.ex:351: Ecto.Changeset.Relation.map_changes/9
    (ecto 3.7.1) lib/ecto/changeset/relation.ex:121: Ecto.Changeset.Relation.cast/5
    (ecto 3.7.1) lib/ecto/changeset.ex:822: Ecto.Changeset.cast_relation/4
    (avro_ex 1.2.0) lib/avro_ex/schema.ex:283: AvroEx.Schema.cast_schema/3
    (avro_ex 1.2.0) lib/avro_ex/schema.ex:39: AvroEx.Schema.parse/2
```

### LINKED ISSUE #61: Records do not support logical types
```elixir
    test "works with logicalType field values" do
      schema = AvroEx.parse_schema!(~S({"type": "record", "name": "Record", "fields": [
          {"type": "long", "name": "timestamp", "logicalType": "timestamp-millis"}
        ]}))

      timestamp = ~U[2022-02-23 20:28:13.498428Z]

      assert {:ok, _} = @test_module.encode(schema, %{timestamp: timestamp})
    end
````

Adding a test like this results in 

```elixir
code:  assert {:ok, _} = @test_module.encode(schema, %{timestamp: timestamp})
left:  {:ok, _}
right: {:error, %AvroEx.EncodeError{message: "Schema Mismatch: Expected value of long, got ~U[2022-02-23 20:28:13.498428Z]"}}
```

### PR DESCRIPTION
**Pull request by davydog187**
The goal of this PR is to

1. Directly support parsing Elixir terms
2. Seamlessly parse Elixir terms or json
3. Detailed error messages for invalid Avro schemas
4. Add better support for all schema types defined in the [Avro 1.11.0 Specification](https://avro.apache.org/docs/current/spec.html).

Closes #40
Closes #60  
Closes #61 
Closes #55

## Schema features
- [x] Primitives
- [x] Unions
- [x] Arrays
- [x] Maps
- [x] Fixed
- [x] Enums
- [x] Records
- [x] Name references
- [ ] Namespace propagation

### CODE REVIEW

**Comment by davydog187** [comment]
I'm having some questions about the spec with respect to how full names are resolved, and what is and isn't allowed in terms of duplicates.

Testing with [avro-js](https://github.com/apache/avro/tree/master/lang/js), I get the following results

### Duplicate field names in a Record
❌ Not allowed

```javascript
> avro.parse({type: "record", name: "a", fields: [{name: "a", type: "string"}, {name: "a", type: "string"}]})
Uncaught Error: duplicate a field name
    at new RecordType (/Users/dave/Development/avro_ex/javascript/node_modules/avro-js/lib/schemas.js:1429:11)
    at /Users/dave/Development/avro_ex/javascript/node_modules/avro-js/lib/schemas.js:136:14
    at Object.createType (/Users/dave/Development/avro_ex/javascript/node_modules/avro-js/lib/schemas.js:137:7)
    at Object.parse (/Users/dave/Development/avro_ex/javascript/node_modules/avro-js/lib/files.js:74:13)
```    

### Duplicate field names in separate Records
✅ Allowed

```javascript
> avro.parse({type: "record", name: "a", fields: [{name: "a", type: "string"}, {name: "b", type: {type: "record", name: "inner", fields: [{name: "a", type: "string"}]}}]})
RecordType {
  _name: 'a',
  _aliases: [],
  _type: 'record',
  _fields: [
    Field { _name: 'a', _type: StringType {}, _aliases: [], _order: 1 },
    Field { _name: 'b', _type: [RecordType], _aliases: [], _order: 1 }
  ],
  _constructor: [Function: a] { getType: [Function (anonymous)] },
  _read: [Function: reada],
  _skip: [Function: skipa],
  _write: [Function: writea],
  _check: [Function: checka]
}
```

However, it does not seem to respect namespaces on Record fields, which tells me I'm either misunderstanding the spec, or this implementation has issues.

**Comment by davydog187** [comment]
It seems that https://github.com/apache/avro/pull/1439 seems to clarify the rules around namespace resolution. I'll dig into that more

**Comment by davydog187** [comment]
Asking for feedback here https://github.com/apache/avro/pull/1439/files#r818203665

File: test/schema_parser_test.exs [hunk 1]
```diff
@@ -0,0 +1,800 @@
+defmodule AvroEx.Schema.ParserTest do
```
Comment (davydog187) [inline test/schema_parser_test.exs:1]: change the name of this file

File: lib/avro_ex.ex [hunk 2]
```diff
@@ -29,38 +29,40 @@ defmodule AvroEx do
...
   Same as `AvroEx.decode_schema/1`, but raises an exception on failure instead of
   returning an error tuple.
   """
-  @spec decode_schema!(Schema.json_schema()) :: Schema.t() | no_return
-  def decode_schema!(json) do
-    case decode_schema(json) do
-      {:ok, schema} -> schema
-      _ -> raise "Parsing schema failed"
+  def decode_schema!(schema) do
+    if is_binary(schema) and not Schema.Parser.primitive?(schema) do
```
Comment (davydog187) [inline lib/avro_ex.ex:60]: @doomspork this ended up being very elegant. Now you can pass anything to `AvroEx.decode_schema!/1` and it will figure out if its json or not

File: lib/avro_ex/schema.ex [hunk 3]
```diff
@@ -305,13 +309,14 @@ defmodule AvroEx.Schema do
   "Record<name=foo>"
   """
   @spec type_name(schema_types()) :: String.t()
-  def type_name(%Primitive{type: nil}), do: "null"
+  def type_name(%Primitive{type: :null}), do: "null"
```
Comment (davydog187) [inline lib/avro_ex/schema.ex:312]: Maybe for another ticket, but this function need a way to get the parent namespace and pass it down to full_name

File: lib/avro_ex/schema/parser.ex [hunk 4]
```diff
@@ -0,0 +1,398 @@
...
+      Enum.reduce(schema.fields, MapSet.new(), fn field, set ->
+        if MapSet.member?(set, field.name) do
+          error({:duplicate_name, field.name, schema})
+        end
+
+        MapSet.put(set, field.name)
+      end)
+    end
+
+    # TODO needs to propagate
```
Comment (davydog187) [inline lib/avro_ex/schema/parser.ex:352]: Last feature to knock out

File: lib/avro_ex/schema/parser.ex [hunk 5]
```diff
@@ -0,0 +1,398 @@
...
+    put_context(context, name, schema)
+  end
+
+  defp capture_context(_type, context), do: context
+
+  defp put_context(context, name, schema) do
+    put_in(context.names[name], schema)
+  end
+
+  defp aliases(%{aliases: aliases, namespace: namespace} = record, parent_namespace)
```
Comment (davydog187) [inline lib/avro_ex/schema/parser.ex:371]: I stole this from `AvroEx.Schema`. I think we will remove that function in a future PR as is only needed in this context

File: lib/avro_ex/schema/record.ex [hunk 6]
```diff
@@ -12,7 +12,9 @@ defmodule AvroEx.Schema.Record do
     field(:doc, :string)
     field(:name, :string)
     field(:namespace, :string)
+    # TODO remove all of these
     field(:qualified_names, {:array, :string}, default: [])
+    # TODO remove
```
Comment (davydog187) [inline lib/avro_ex/schema/record.ex:17]: metadata is valid

File: lib/avro_ex/schema/record.ex [hunk 7]
```diff
@@ -12,7 +12,9 @@ defmodule AvroEx.Schema.Record do
     field(:doc, :string)
     field(:name, :string)
     field(:namespace, :string)
+    # TODO remove all of these
```
Comment (davydog187) [inline lib/avro_ex/schema/record.ex:15]: will create a ticket for this

File: CHANGELOG.md [hunk 8]
```diff
@@ -4,6 +4,10 @@
 
 ### Changed
 * `AvroEx.encode/2` now returns `{:error, AvroEx.EncodeError.t()}` in the case of an error
+* Primitive integer types now represented as `%Primitive{type: :int}` instead of `%Primitive{type: :integer}`
+* Primitive null types now represented as `%Primitive{type: :null}` instead of `%Primitive{type: nil}`
+* Schema parser now supports Elixir terms and will strictly validate the schema
+* Dropped Ecto as a dependency
```
Comment (davydog187) [inline CHANGELOG.md:10]: remove from this PR, will do in the next one

File: lib/avro_ex/schema/parser.ex [hunk 9]
```diff
@@ -0,0 +1,398 @@
+defmodule AvroEx.Schema.Parser do
+  @doc false
+  alias AvroEx.Schema
+  alias AvroEx.Schema.{Array, Context, Fixed, Primitive, Record, Reference, Union}
+  alias AvroEx.Schema.Enum, as: AvroEnum
+  alias AvroEx.Schema.Map, as: AvroMap
+
+  # TODO convert to atom
```
Comment (davydog187) [inline lib/avro_ex/schema/parser.ex:8]: Get this done
